name: Qodana
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.java'
    branches:
      - main
  push:
    paths:
      - '**.java'
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.4
        with:
          linter: jetbrains/qodana-jvm
          fail-threshold: 1
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json